### ISSUE TITLE
jvm-driver-8.15.0 detected as Trojan by BitDefender (Probably False Positive)

### ISSUE THREAD

**Issue by nref-dan** [burningwave/jvm-driver#12]
Hi Team - I'm having a problem whereby the JVM driver is being picked up as a Trojan by BitDefender (Trojan.GenericKD.72231710).

I'm 99.9% certain this is a false positive (and has only recently started happening), but I can't grab the file to submit for false positive report, or mark it as an exclusion, as the AV deletes it before I can get hold of it. Is there any chance you could submit this to BitDefender to remove the false flag?

For what it's worth, the installation is done via Maven for IntelliJ.

Thanks.

**Comment by Roberto-Gentili** [comment]
The jvm driver is not dangerous in itself, **but a developer can also use it for malicious purposes**, which is why I guess some antiviruses are starting to consider it dangerous

**Comment by Roberto-Gentili** [comment]
The Java driver is not dangerous itself, **but a developer can also use it for malicious purposes**, which is why I imagine some antiviruses are starting to consider it dangerous. In your case you can try deactivating real-time scanning and try adding it to the exceptions and then reactivating real-time scanning: if you decide to proceed in this way, however, it is at your own risk

**Comment by Roberto-Gentili** [comment]
The JVM driver is not dangerous itself, **but a developer can also use it for malicious purposes**, and this is why I think some antiviruses are starting to consider it dangerous. In your case you can try deactivating real-time scanning and try adding it to the exceptions and then reactivating real-time scanning: if you decide to proceed in this way, however, it is at your own risk

**Comment by nref-dan** [comment]
Hi Roberto, thanks for your reply.

Yes, I added an exception for it for development purposes, I was really just trying to highlight it with you so that you had the opportunity to submit it to the relevant security providers to get it whitelisted.

Feel free to close this issue though.
