### ISSUE TITLE
Short field handlers are absent in NativeExecutor

### ISSUE THREAD

**Issue by JaynLau** [burningwave/jvm-driver#4]
There is none method to get or set short field in NativeExecutor now.

**Comment by Roberto-Gentili** [comment]
I fixed the problem but I'm unable to release: [I obtain this error on ubuntu x64](https://github.com/burningwave/jvm-driver/actions/runs/2466532267)

`org.burningwave.jvm.test.NativeDriverTest.getAndSetDirectVolatileTestOne  Time elapsed: 0.012 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: 'void org.burningwave.jvm.NativeExecutor.setShortFieldValue(java.lang.Object, java.lang.reflect.Field, java.lang.Short)'
	at org.burningwave.jvm.test.NativeDriverTest.getAndSetDirectVolatileTestOne(NativeDriverTest.java:38)`

This is the [NativeExecutor.cpp](https://github.com/burningwave/jvm-driver/blob/main/native/src/main/c-c%2B%2B/org/burningwave/jvm/NativeExecutor.cpp) and this is the [NativeExecutor.java](https://github.com/burningwave/jvm-driver/blob/main/java/src/main/java/org/burningwave/jvm/NativeExecutor.java): what i added seems correct to me, can you see if there is any error?

**Comment by JaynLau** [comment]
The method signature seems to be incorrect.

![image](https://user-images.githubusercontent.com/1670721/172798955-b9d0f94e-f625-4349-9471-a6f235f016b1.png)

**Comment by Roberto-Gentili** [comment]
I found the problem: it's on the [pom.xml](https://github.com/burningwave/jvm-driver/blob/main/native/pom.xml): when the [workflow](https://github.com/burningwave/jvm-driver/blob/main/.github/workflows/%5BA%5D%20build%20and%20test%2C%20release%20if%20requested.yml) is launched on ubuntu x64 it executes only the task with id [`compile native for aarch64`](https://github.com/burningwave/jvm-driver/blob/ca004f89163285c8909b810d2b122f154f0b297f/native/pom.xml#L124) and it doesn't execute the [main task](https://github.com/burningwave/jvm-driver/blob/ca004f89163285c8909b810d2b122f154f0b297f/native/pom.xml#L201)

**Comment by Roberto-Gentili** [comment]
Ok, I solved: check the [progress of the release](https://github.com/burningwave/jvm-driver/actions/runs/2467379209)

**Comment by JaynLau** [comment]
Ok, I will check it after release. Why using boxed types to handle primitive types?

**Comment by Roberto-Gentili** [comment]
To avoid checks and possible conversions in the JNI layer if a value received in input is of primitive type and the class field is not and vice versa

**Comment by JaynLau** [comment]
It seems so. I will do a performance test to compare the two implementations when I have time.

**Comment by Roberto-Gentili** [comment]
> It seems so. I will do a performance test to compare the two implementations when I have time.

Ok, you're welcome. Thank you very much

**Comment by JaynLau** [comment]
Hi, I did a performance test today between your implementation and the none boxing/unboxing implementation.

Your implementation.
```
Benchmark                             Mode  Cnt      Score     Error   Units
NativeExecutorBench.get01_primitive  thrpt    5   6443.048 ± 349.801  ops/ms
NativeExecutorBench.get02_object     thrpt    5  17465.356 ± 203.896  ops/ms
NativeExecutorBench.set01_primitive  thrpt    5   6551.346 ± 109.559  ops/ms
NativeExecutorBench.set02_object     thrpt    5  20479.006 ± 224.800  ops/ms
```
The none boxing/unboxing implementation.
```
Benchmark                                      Mode  Cnt      Score     Error   Units
NativeExecutorBench.get01_primitive           thrpt    5  32597.013 ± 459.114  ops/ms
NativeExecutorBench.get01_primitive_directly  thrpt    5  35214.925 ± 789.498  ops/ms
NativeExecutorBench.get02_object              thrpt    5  17177.163 ± 457.885  ops/ms
NativeExecutorBench.get02_object_directly     thrpt    5  17462.458 ± 233.682  ops/ms
NativeExecutorBench.set01_primitive           thrpt    5  23135.374 ± 176.035  ops/ms
NativeExecutorBench.set02_primitive_directly  thrpt    5  26144.575 ± 300.973  ops/ms
NativeExecutorBench.set03_object              thrpt    5  19641.708 ± 275.529  ops/ms
NativeExecutorBench.set04_object_directly     thrpt    5  20433.885 ±  81.209  ops/ms
```

In my optimization implementation, I moved all checks to Java, using primitive types and doing the minimum necessary operations in JNI.

Should I create a pull request to review my code?

**Comment by Roberto-Gentili** [comment]
Great job, you must create a pull request, but first make sure you have updated the project because I also made some changes a few days ago. I'll wait for your pull request

**Comment by Roberto-Gentili** [comment]
... Or I can add you as a contributor to the project so that you can directly submit changes and also execute releases: How do you think about?

**Comment by JaynLau** [comment]
I have created a PR [Improve performance for primitive types](https://github.com/burningwave/jvm-driver/pull/5).

**Comment by Roberto-Gentili** [comment]
I merged and pushed your changes: I started compiling and testing native modules: [here the progress](https://github.com/burningwave/jvm-driver/actions/runs/2487978977)

Would you like to become a collaborator on the project so that you can directly make changes and make releases?
For example, you can enrich the [home page](https://github.com/burningwave/jvm-driver) with your own tests.

**Comment by JaynLau** [comment]
It's my pleasure! ^_^

**Comment by Roberto-Gentili** [comment]
Ok, tests are ok. Now to release you need only to push with the comment "Releasing new version":

![image](https://user-images.githubusercontent.com/91185696/173346581-2c1e115b-71f4-43b7-8e39-d4a6293f1836.png)

On the other hand, if you are going to make changes to the native module and want to test them, you need to do the same with the comment "Generating external artifacts"

**Comment by Roberto-Gentili** [comment]
Ok, tests are ok. Now to release you need only to push with the comment "Releasing new version":

![image](https://user-images.githubusercontent.com/91185696/173346581-2c1e115b-71f4-43b7-8e39-d4a6293f1836.png)



</br>
</br>

On the other hand, **if you are going to make changes to the native module and want to test them**, you need to do the same with the comment "Generating external artifacts"


I await your release to update [Burningwave Core](https://burningwave.github.io/core/) dependencies

**Comment by Roberto-Gentili** [comment]
Ok, tests are ok. Now to release you need only to push on the main branch with the comment "Releasing new version":

![image](https://user-images.githubusercontent.com/91185696/173346581-2c1e115b-71f4-43b7-8e39-d4a6293f1836.png)



</br>
</br>

On the other hand, **if you are going to make changes to the native module and want to test them**, you need to do the same with the comment "Generating external artifacts".

These push trigger [GitHub actions](https://github.com/burningwave/jvm-driver/actions) that perform native module generation, testing and release.


I await your release to update [Burningwave Core](https://burningwave.github.io/core/) dependencies

**Comment by Roberto-Gentili** [comment]
Don't worry, there is no rush. I will await your release. Have a good rest

**Comment by Roberto-Gentili** [comment]
I saw you released: well done! 

Feel free to improve this project as you see fit. Burningwave JVM Driver compared to Narcissus has the native module also for aarch64 which, however, must be tested. Some improvements that can be made to this project are for example:

- compile the native module for other platforms (at the moment the native module is compiled for the configurations indicated in the [Overview](https://github.com/burningwave/jvm-driver#overview))
- add Javadoc
- add tests for aarch64 in the [github action](https://github.com/burningwave/jvm-driver/blob/main/.github/workflows/%5BA%5D%20build%20and%20test%2C%20release%20if%20requested.yml)

All this without obligation, and if you are able to make improvements to the project you are welcome :-)

**Comment by JaynLau** [comment]
OK, I'm excited to contribute some ideas and code to this project.

**Comment by Roberto-Gentili** [comment]
Great! :-)
If you use Skype add me: this is my account: roberto.gentili.1980@gmail.com
